/**
 * PenguinHarness plugin library: the built-in plugins and the loader that reads them (part
 * of core — hooks, skills and their loading all live in one SDK).
 *
 * A plugin is its own npm package (`@penguinharness/<name>`, `plugins/<name>/` in the repo;
 * resolved through Node from the host package's dependency list — see pluginRoots): a
 * directory carrying a `plugin.json` manifest, an `icon.svg` beside it (every built-in plugin
 * ships one; it is the icon of everything the plugin ships), and any of two kinds of content:
 * skills (`skills/<name>/SKILL.md`, installed into an Agent's `agent_state/skills/`) and a
 * hook package (`hooks/*.mjs`, installed into `agent_state/hooks/<plugin>/` together with a
 * generated `hooks.json`). The files are the runtime source of truth — read and parsed on
 * every call, no caching (files are small, calls are infrequent) — so editing a file takes
 * effect immediately. They are committed content reached through declared dependencies, so
 * anything that fails to load is a broken install or a broken plugin and throws with the
 * path — never a silently smaller library. Only the category manifest (id and titles) is
 * code; install / uninstall / scan live in core's state layer.
 *
 * Versions are dates with a sequence number, `YYYY-MM-DD.N` (see PLUGIN_VERSION_PATTERN and
 * comparePluginVersions). plugin.json is the single metadata holder: a library SKILL.md's frontmatter
 * carries only `name` and `description`, and the loader stamps the plugin's version and UI short
 * descriptions into each skill's metadata and installable content (the installed copy carries the
 * full frontmatter, generated — the way hooks.json is).
 *
 * Docs: packages/docs/content/skills.{zh,en}.md (site path /docs/skills) documents the plugin
 * format, the versions and the built-in library.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

/** A skill's metadata. A library SKILL.md's frontmatter carries only `name` and `description`; the short descriptions and `version` are stamped from plugin.json by the loader (installed copies then carry the full generated frontmatter, which is what the installed-side readers parse). */
export interface SkillMetadata {
  /** Skill name (matches its containing directory name). */
  name: string;
  /** One-line description; injected into the model prompt via `{{SKILL_METADATA}}`. */
  description: string;
  /** UI short description (frontmatter `short_description`, optional): preferred in compact spots like cards, falls back to the full description if missing; not injected into the prompt. */
  shortDescription?: string;
  /** Chinese short description (frontmatter `short_description_zh`, optional). */
  shortDescriptionZh?: string;
  /** Version, `YYYY-MM-DD.N`; an absent or malformed frontmatter version reads as "" (older than any real version). */
  version: string;
}

/** A skill in the library: metadata + full SKILL.md content (including frontmatter, written as-is on install). */
export interface LibrarySkill extends SkillMetadata {
  content: string;
  /** The plugin's raw `icon.svg`, stamped onto every skill by the loader — a skill has no icon of its own — and written as `icon.svg` beside SKILL.md on install, so the installed copy carries it; absent when the plugin ships none. */
  icon?: string;
  /**
   * Optional auxiliary files the SKILL.md references (e.g. `reference/API.md`), keyed by
   * POSIX-relative path within the skill directory; every entry except the top-level SKILL.md
   * (its own field) and a top-level icon.svg (reserved: the plugin's icon is what installs
   * there). Written alongside SKILL.md on install (subdirectories preserved). Read as UTF-8
   * text — library content is committed text; the field is omitted when a skill has no extra
   * files.
   */
  files?: Record<string, string>;
}

/** One hook script entry: `command` is a path relative to the plugin's `hooks/` directory, run with Node; `timeout` in seconds (core's default applies when absent). */
export interface HookCommand {
  command: string;
  timeout?: number;
}

/**
 * The manifest an installed hook package carries (`agent_state/hooks/<plugin>/hooks.json`),
 * generated by the installer from plugin.json: identity and display fields, plus one script
 * list per hook point (`stop`, `pre_tool_use`, `user_prompt`). The plugin's icon is not part
 * of it: the installer writes `icon.svg` beside the manifest instead.
 */
export interface HookManifest {
  name: string;
  description: string;
  description_zh?: string;
  version: string;
  /** Stop commands, consulted after every Task of a run. */
  stop: HookCommand[];
  /** Pre-tool-use commands, consulted before each tool call's approval. */
  pre_tool_use: HookCommand[];
  /** User-prompt expansion commands, run by the host when it accepts a prompt for the flow the package owns (goal mode's start). */
  user_prompt: HookCommand[];
}

/** A plugin's hook package as read from the library: the manifest to install and the `hooks/` files (relative path → text). */
export interface LibraryHooks {
  manifest: HookManifest;
  files: Record<string, string>;
}

/** A plugin in the library: the manifest fields plus the content it ships. */
export interface LibraryPlugin {
  /** Plugin name (its directory name). */
  name: string;
  /** English one-line description (plugin.json `description`). */
  description: string;
  /** Chinese description (plugin.json `description_zh`, optional). */
  descriptionZh?: string;
  /** UI short descriptions (plugin.json `short_description(_zh)`, optional). */
  shortDescription?: string;
  shortDescriptionZh?: string;
  /** `YYYY-MM-DD.N`. */
  version: string;
  /** Category id (see PLUGIN_CATEGORIES); absent or unknown → the "other" group. */
  category?: string;
  /** Whether default_agent gets this plugin at creation (plugin.json `preinstall`, default true). */
  preinstall: boolean;
  /** Raw `icon.svg` beside plugin.json — every built-in plugin ships one. It is the icon of everything the plugin ships: stamped onto each skill and written beside an installed hook package. */
  icon?: string;
  skills: LibrarySkill[];
  hooks?: LibraryHooks;
}

/** Category manifest entry: id and titles (Chinese optional, displayed per UI language). */
export interface PluginCategory {
  id: string;
  title: string;
  titleZh?: string;
}

/** Grouping result: category metadata + member plugins read from library files. */
export interface ResolvedPluginGroup extends PluginCategory {
  plugins: LibraryPlugin[];
}

/** Character rule for plugin, skill and hook names (directory names): prevents path traversal (exported for the server's archive-install validation). */
export const PLUGIN_NAME_PATTERN = /^[A-Za-z0-9_-]+$/;

/** Version format: an ISO date and a sequence number, e.g. `2026-08-29.1`. */
export const PLUGIN_VERSION_PATTERN = /^\d{4}-\d{2}-\d{2}\.\d+$/;

/**
 * Orders two versions: by date, then by sequence number (numeric, so `.10` follows `.9`). A
 * string that is not a version (the empty string an unversioned install reads as, a legacy
 * natural number) sorts before every real version, so anything in the library counts as newer.
 */
export function comparePluginVersions(a: string, b: string): number {
  const va = PLUGIN_VERSION_PATTERN.test(a);
  const vb = PLUGIN_VERSION_PATTERN.test(b);
  if (!va || !vb) return Number(va) - Number(vb);
  const [da, na] = a.split(".");
  const [db, nb] = b.split(".");
  if (da !== db) return da! < db! ? -1 : 1;
  return Number(na) - Number(nb);
}

/**
 * Parses the frontmatter at the start of SKILL.md: only recognizes `key: value` lines inside the
 * first `---` block (split on the first colon, value trimmed, values may themselves contain colons);
 * all fields are scalars, no YAML dependency needed.
 * Error tolerance: returns null if the `---` block or name is missing; a version that is not
 * `YYYY-MM-DD.N` reads as "".
 */
export function parseSkillFrontmatter(content: string): SkillMetadata | null {
  // Strip a possible UTF-8 BOM (may be introduced by editors when manually editing an installed SKILL.md); CRLF is handled by \r?\n.
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(content.replace(/^﻿/, ""));
  if (!match) return null;
  const fields: Record<string, string> = {};
  for (const line of match[1]!.split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx <= 0) continue;
    const key = line.slice(0, idx).trim();
    if (key) fields[key] = line.slice(idx + 1).trim();
  }
  const name = fields["name"];
  if (!name) return null;
  const version = fields["version"] ?? "";
  const shortDescription = fields["short_description"];
  const shortDescriptionZh = fields["short_description_zh"];
  return {
    name,
    description: fields["description"] ?? "",
    // short_description(_zh) is optional: omitted when absent (undefined keys aren't set).
    ...(shortDescription !== undefined ? { shortDescription } : {}),
    ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
    version: PLUGIN_VERSION_PATTERN.test(version) ? version : "",
  };
}

/** npm-name prefix of the per-plugin packages (the host package's dependencies name them). */
const PLUGIN_PKG_PREFIX = "@penguinharness/";

/**
 * The host package: the package whose `dependencies` name the plugin packages — `packages/core`
 * from source or dist, and the bundling package's own root wherever core is inlined (the CLI
 * bundle, the desktop server bundle). Looked for above this module first, then above the
 * running program (`process.argv[1]`): a hot-pushed platform bundle sits in the data root's
 * store, where nothing above it is a package, and the plugins it can offer are the ones
 * installed beside the program that booted it. The first package.json naming a plugin
 * package wins; failing that, the first package.json at all (an empty library, with a root
 * to name in errors); failing that, null.
 *
 * Found on first use and never at import: the bundle has to LOAD on a machine that has no
 * host package, and the library call is then what fails, naming both places it looked.
 */
interface HostPackage {
  root: string;
  /** Resolves the plugin packages the way a `require` from the host package would. */
  require: NodeJS.Require;
}

const LOADER_DIR = path.dirname(fileURLToPath(import.meta.url));

function programDir(): string | null {
  const entry = process.argv[1];
  return typeof entry === "string" && entry !== "" ? path.dirname(path.resolve(entry)) : null;
}

function findHostPackage(): HostPackage | null {
  let first: HostPackage | null = null;
  for (const start of [LOADER_DIR, programDir()]) {
    if (start === null) continue;
    for (let dir = start; ;) {
      const file = path.join(dir, "package.json");
      if (fs.existsSync(file)) {
        const candidate: HostPackage = { root: dir, require: createRequire(file) };
        if (Object.keys(readDependencies(candidate)).some((d) => d.startsWith(PLUGIN_PKG_PREFIX)))
          return candidate;
        first ??= candidate;
        break;
      }
      const parent = path.dirname(dir);
      if (parent === dir) break;
      dir = parent;
    }
  }
  return first;
}

let host: HostPackage | null | undefined;
function hostPackage(): HostPackage {
  if (host === undefined) host = findHostPackage();
  if (host === null) {
    const program = programDir();
    throw new Error(
      `No package.json above the plugin loader at ${LOADER_DIR}` +
        (program === null ? "" : ` or above the program at ${program}`),
    );
  }
  return host;
}

/** The host package's `dependencies`, read fresh — the same file its own `require` resolves from. */
function readDependencies(pkg: HostPackage): Record<string, string> {
  const parsed = JSON.parse(fs.readFileSync(path.join(pkg.root, "package.json"), "utf8")) as {
    dependencies?: Record<string, string>;
  };
  return parsed.dependencies ?? {};
}

/**
 * Where the plugin directories live, name → absolute root. Each plugin is its own npm package
 * (`@penguinharness/<name>`, `plugins/<name>/` in the repo): the host package's `dependencies`
 * name them (core, the CLI, and the desktop app — whose packaged manifest keeps that field
 * and nothing else, so `devDependencies` would not survive into an installer), and each is
 * resolved through Node from the host package (hostPackage), so the lookup walks the same
 * `node_modules` chain a `require` from there would: the workspace, an npm install, the
 * packed desktop app (electron-builder collects the declared packages into its node_modules)
 * and the program a hot-pushed platform booted from all land on their own copy. Read fresh
 * on every call, like the plugin files themselves.
 */
function pluginRoots(): Map<string, string> {
  const roots = new Map<string, string>();
  const pkg = hostPackage();
  for (const dep of Object.keys(readDependencies(pkg))) {
    if (!dep.startsWith(PLUGIN_PKG_PREFIX)) continue;
    let manifest: string;
    try {
      manifest = pkg.require.resolve(`${dep}/package.json`);
    } catch (err) {
      // A declared plugin that Node cannot find is a broken install (the deployment did not
      // carry the package), not a smaller library.
      throw new Error(
        `Plugin package ${dep} is declared in ${pkg.root}/package.json but cannot be resolved: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
    roots.set(dep.slice(PLUGIN_PKG_PREFIX.length), path.dirname(manifest));
  }
  return roots;
}

/**
 * Recursively collects a directory's files as text keyed by POSIX-relative path, skipping the
 * names in `except` at the top level. Symlinks and other non-regular entries are skipped.
 * Returns undefined when the directory has no such files.
 */
function readDirFiles(dir: string, except: readonly string[]): Record<string, string> | undefined {
  const files: Record<string, string> = {};
  const walk = (abs: string, rel: string): void => {
    for (const entry of fs.readdirSync(abs, { withFileTypes: true })) {
      const childRel = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(path.join(abs, entry.name), childRel);
      } else if (entry.isFile()) {
        if (rel === "" && except.includes(entry.name)) continue;
        files[childRel] = fs.readFileSync(path.join(abs, entry.name), "utf8");
      }
    }
  };
  walk(dir, "");
  return Object.keys(files).length > 0 ? files : undefined;
}

/**
 * Reads one skill directory: name from the directory (overriding frontmatter), SKILL.md verbatim,
 * and every other file as auxiliary content. The icon is not read here: a skill has none of
 * its own, and stampSkill gives it the plugin's.
 */
function readSkillDir(dir: string, name: string): LibrarySkill {
  const file = path.join(dir, "SKILL.md");
  const content = fs.readFileSync(file, "utf8");
  const meta = parseSkillFrontmatter(content);
  if (!meta) throw new Error(`Library skill ${file} has no frontmatter with a name`);
  const files = readDirFiles(dir, ["SKILL.md", "icon.svg"]);
  return { ...meta, name, content, ...(files !== undefined ? { files } : {}) };
}

/**
 * Resolves a library skill against its plugin: the plugin's version and UI short descriptions
 * are the skill's (a library SKILL.md carries only `name` and `description`), its icon
 * becomes the skill's, and the installable `content` gets the full frontmatter regenerated in
 * canonical field order — the installed copy is self-describing (update checks read its
 * `version`, the UI its short descriptions and icon) the same way an installed hook package's
 * hooks.json is generated.
 */
function stampSkill(
  skill: LibrarySkill,
  plugin: {
    shortDescription?: string;
    shortDescriptionZh?: string;
    version: string;
    icon?: string;
  },
): LibrarySkill {
  const { shortDescription, shortDescriptionZh } = plugin;
  const front = [
    "---",
    `name: ${skill.name}`,
    `description: ${skill.description}`,
    ...(shortDescription !== undefined ? [`short_description: ${shortDescription}`] : []),
    ...(shortDescriptionZh !== undefined ? [`short_description_zh: ${shortDescriptionZh}`] : []),
    `version: ${plugin.version}`,
    "---",
  ].join("\n");
  const body = skill.content.replace(/^\ufeff?---\r?\n[\s\S]*?\r?\n---/, "");
  return {
    ...skill,
    ...(shortDescription !== undefined ? { shortDescription } : {}),
    ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
    version: plugin.version,
    ...(plugin.icon !== undefined ? { icon: plugin.icon } : {}),
    content: `${front}${body}`,
  };
}

/** The plugin.json shape: the single metadata holder of a plugin (see the module header). */
interface PluginManifestFile {
  description: string;
  description_zh?: string;
  short_description?: string;
  short_description_zh?: string;
  /** `YYYY-MM-DD.N`. */
  version: string;
  category?: string;
  /** Default true. */
  preinstall?: boolean;
  /** One command list per hook point the plugin's hook package answers at. */
  hooks?: {
    stop?: HookCommand[];
    pre_tool_use?: HookCommand[];
    user_prompt?: HookCommand[];
  };
}

/** Reads one plugin directory. */
function readPluginDir(name: string, dir: string): LibraryPlugin {
  const manifestFile = path.join(dir, "plugin.json");
  const manifest = JSON.parse(fs.readFileSync(manifestFile, "utf8")) as PluginManifestFile;
  if (!PLUGIN_VERSION_PATTERN.test(manifest.version)) {
    throw new Error(`${manifestFile}: version must be YYYY-MM-DD.N, got ${manifest.version}`);
  }
  const {
    description,
    description_zh: descriptionZh,
    short_description: shortDescription,
    short_description_zh: shortDescriptionZh,
    version,
  } = manifest;
  const skills: LibrarySkill[] = [];
  const skillsDir = path.join(dir, "skills");
  if (fs.existsSync(skillsDir)) {
    for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
      if (entry.isDirectory())
        skills.push(readSkillDir(path.join(skillsDir, entry.name), entry.name));
    }
    skills.sort((a, b) => a.name.localeCompare(b.name));
  }
  let icon: string | undefined;
  try {
    icon = fs.readFileSync(path.join(dir, "icon.svg"), "utf8");
  } catch {
    // Built-in plugins all ship one; a plugin without it falls back to the kind's glyph in the UI.
  }
  const hooksDir = path.join(dir, "hooks");
  const hookFiles = fs.existsSync(hooksDir) ? readDirFiles(hooksDir, []) : undefined;
  const hooks: LibraryHooks | undefined =
    hookFiles !== undefined
      ? {
          manifest: {
            name,
            description,
            ...(descriptionZh !== undefined ? { description_zh: descriptionZh } : {}),
            version,
            stop: manifest.hooks?.stop ?? [],
            pre_tool_use: manifest.hooks?.pre_tool_use ?? [],
            user_prompt: manifest.hooks?.user_prompt ?? [],
          },
          files: hookFiles,
        }
      : undefined;
  return {
    name,
    description,
    ...(descriptionZh !== undefined ? { descriptionZh } : {}),
    ...(shortDescription !== undefined ? { shortDescription } : {}),
    ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
    version,
    ...(manifest.category !== undefined ? { category: manifest.category } : {}),
    preinstall: manifest.preinstall !== false,
    ...(icon !== undefined ? { icon } : {}),
    skills: skills.map((skill) =>
      stampSkill(skill, {
        ...(shortDescription !== undefined ? { shortDescription } : {}),
        ...(shortDescriptionZh !== undefined ? { shortDescriptionZh } : {}),
        version,
        ...(icon !== undefined ? { icon } : {}),
      }),
    ),
    ...(hooks !== undefined ? { hooks } : {}),
  };
}

/** Reads every plugin in the library (one per plugin package, see pluginRoots), sorted by name. */
export function loadLibraryPlugins(): LibraryPlugin[] {
  return [...pluginRoots()]
    .map(([name, dir]) => readPluginDir(name, dir))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** The plugins default_agent installs at initialization: every library plugin except those whose manifest sets `preinstall: false`. */
export function loadPreinstalledPlugins(): LibraryPlugin[] {
  return loadLibraryPlugins().filter((plugin) => plugin.preinstall);
}

/** Reads a single library plugin by name; undefined when the library has no such plugin (names are looked up, never joined into a path). */
export function libraryPlugin(name: string): LibraryPlugin | undefined {
  const dir = pluginRoots().get(name);
  return dir !== undefined ? readPluginDir(name, dir) : undefined;
}

/** Finds a library skill by its own name (across every plugin), with the plugin that ships it. */
export function librarySkill(
  name: string,
): { plugin: LibraryPlugin; skill: LibrarySkill } | undefined {
  for (const plugin of loadLibraryPlugins()) {
    const skill = plugin.skills.find((s) => s.name === name);
    if (skill) return { plugin, skill };
  }
  return undefined;
}

/**
 * Category manifest, in display order. Categories group by audience, not by technology: a
 * hook-only plugin sits with the skills it serves the same audience as (goal mode and
 * continual learning are office productivity), and agent tuning is AI app development.
 * Docs: /docs/skills § "Built-in library".
 */
export const PLUGIN_CATEGORIES: PluginCategory[] = [
  { id: "office-productivity", title: "Office Productivity", titleZh: "办公效率" },
  { id: "software-development", title: "Software Development", titleZh: "软件开发" },
  { id: "ai-app-development", title: "AI App Development", titleZh: "AI 应用开发" },
];

/**
 * Groups plugins by category in PLUGIN_CATEGORIES order (members sorted by name; an empty
 * category is omitted); plugins with no or an unknown category land in an Other group appended
 * at the end (only when non-empty). A pure function, the testable core of loadPluginGroups.
 */
export function groupPlugins(all: LibraryPlugin[]): ResolvedPluginGroup[] {
  const groups: ResolvedPluginGroup[] = [];
  const known = new Set(PLUGIN_CATEGORIES.map((c) => c.id));
  for (const category of PLUGIN_CATEGORIES) {
    const members = all
      .filter((p) => p.category === category.id)
      .sort((a, b) => a.name.localeCompare(b.name));
    if (members.length > 0) groups.push({ ...category, plugins: members });
  }
  const others = all
    .filter((p) => p.category === undefined || !known.has(p.category))
    .sort((a, b) => a.name.localeCompare(b.name));
  if (others.length > 0) {
    groups.push({ id: "other", title: "Other", titleZh: "其他", plugins: others });
  }
  return groups;
}

/** Reads the library and groups it (see groupPlugins). */
export function loadPluginGroups(): ResolvedPluginGroup[] {
  return groupPlugins(loadLibraryPlugins());
}
